# Generated by Django 5.2.4 on 2025-08-21 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'permissions': [('can_view_stocks', 'Can view stocks'), ('can_manage_stocks', 'Can manage stocks')],
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_portfolios', 'Can view portfolios'), ('can_manage_portfolios', 'Can manage portfolios')]},
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'permissions': [('can_view_portfolios', 'Can view portfolios'), ('can_manage_portfolios', 'Can manage portfolios')],
            },
        ),
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.stock')),
            ],
            options={
                'unique_together': {('portfolio', 'stock')},
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stocks',
            field=models.ManyToManyField(related_name='portfolios_stocks', through='auth_user.Holdings', to='auth_user.stock'),
        ),
    ]
