# Generated by Django 5.2.4 on 2025-09-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_stock_alter_customuser_options_portfolio_holdings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
